version: "3"

services:
  php-cli:
    build:
      context: './../'
      dockerfile: ./docker/Dockerfile
    restart: 'no'
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./../:/var/www/html:cached
